
output: "."
source_directory: ../
author: Zhuhao Wang
readme: ../README.md
github_url: https://github.com/zhuhaow/NEKit
min_acl: internal
module: NEKit

theme: fullwidth

custom_categories:
  - name: Proxy Server
    children:
      - ProxyServer
      - GCDProxyServer
      - GCDSOCKS5ProxyServer
      - GCDHTTPProxyServer

  - name: Socket
    children:
      - Tunnel
      - TunnelDelegate
      - SocketProtocol
      - SocketDelegate
      - ProxySocket
      - DirectProxySocket
      - HTTPProxySocket
      - SOCKS5ProxySocket
      - AdapterSocket
      - DirectAdapter
      - HTTPAdapter
      - SecureHTTPAdapter
      - ShadowsocksAdapter
      - SpeedAdapter
      - SocketStatus

  - name: AdapterSocketFactory
    children:
      - AdapterFactoryManager
      - AdapterFactory
      - DirectAdapterFactory
      - ServerAdapterFactory
      - AuthenticationServerAdapterFactory
      - HTTPAdapterFactory
      - HTTPAuthenticationAdapterFactory
      - SecureHTTPAdapterFactory
      - ShadowsocksAdapterFactory
      - SpeedAdapterFactory

  - name: Raw Socket
    children:
      - SocketBaseType
      - RawSocketFactory
      - RawTCPSocketProtocol
      - RawTCPSocketDelegate
      - GCDTCPSocket
      - NWTCPSocket
      - TUNTCPSocket
      - NWUDPSocket

  - name: Rule
    children:
       - RuleManager
       - Rule
       - DirectRule
       - AllRule
       - CountryRule
       - ListRule
       - DNSFailRule

  - name: Connect Message
    children:
      - ConnectSession
      - ConnectResponse
      - HTTPHeader

  - name: IP Stack
    children:
      - TUNInterface
      - IPStackProtocol
      - TCPStack
      - UDPDirectStack

  - name: DNS
    children:
      - DNSEnum
      - DNSClass
      - DNSMessageType
      - DNSReturnStatus
      - DNSType
      - DNSMessage
      - DNSNameConverter
      - DNSQuery
      - DNSResource
      - DNSResolverProtocol
      - DNSResolver
      - DNSResolverDelegate
      - UDPDNSResolver
      - DNSServer
      - DNSSession
      - DNSSessionMatchResult
      - DNSSessionMatchType

  - name: IP Packet
    children:
      - IPVersion
      - TransportProtocol
      - IPPacket
      - TransportProtocolParserProtocol
      - UDPProtocolParser

  - name: Event
    children:
      - EventType
      - ProxyServerEvent
      - TunnelEvent
      - AdapterSocketEvent
      - ProxySocketEvent
      - RuleMatchEvent
      - Observer
      - ObserverFactory

  - name: Observer for Debug
    children:
      - DebugObserverFactory
      - DebugTunnelObserver
      - DebugProxySocketObserver
      - DebugAdapterSocketObserver
      - DebugProxyServerObserver
      - DebugRuleManagerObserver

  - name: Configuration Parser
    children:
      - Configuration
      - AdapterFactoryParser
      - RuleParser
      - ConfigurationParserError

  - name: Utilities
    children:
      - Atomic
      - Box
      - BinaryReadable
      - BinaryDataScanner
      - Checksum
      - HTTPAuthentication
      - HTTPStreamScanner
      - IPAddress
      - IPv4Address
      - IPv4Pool
      - Port
      - StreamScanner
      - Utils
