language: objective-c
osx_image: xcode9
cache:
  directories:
  - Carthage
install:
- bin/bootstrap-if-needed
- gem install scan
script:
- scan --scheme NEKit-macOS
- scan --scheme NEKit-iOS
after_success:
- bash <(curl -s https://codecov.io/bash)
- "./docs/build_docs.sh"
before_deploy:
- carthage build --no-skip-current
- carthage archive NEKit
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: DZC5vAZl8nbvPsVnYTf3zmh9/x7Y8hl3b2gSMklVtmwg2RkQ+OlaiJmpIzwiCY1iUkEBZ4X/5vRj/Ed07s648atJMkp8Y0WXNKzsLAZXmHNd+2h99IVx7PC112mj8qQTmoihUle5+vANthHZoG1jti59siHeFgpLb4BEQl1iCRESy4tl6XQZcgRwphTeEwyNWuveBToBdIx2piCAavwlw++YPsD3+NFgyqy8gZsiueins2sX7hpcZDNKjfDKSO7Lfi3YSqvEXF6xYrmwG7TO25Jf6iCurQho/Gc74n0RwjJgBgfGm5SIdzmK+Est061xW1iQQzEUF1RN/kB6kKtqVjxxdGNg7GhTEpXBII0GyCdsoIlPSxC40xz+3QAR6xHkcEEygle39QSIIza9hBX3weKYABZFjnCQz2i/hGnN+KBurgNLeBJeOUbNN9Dzct3WPV72yebiOMLl+lnPuK88NB5mRR5Gq9ZFtBp86JBNmStWb041Dd8jY6tTqsLd253phosVFmClvndauQayuYUVLAKx9csKNwhyrVtpjdsniiRSzHn8E+zzi4jvC7KEXDUym5Jq8qvJMb0c1itv4A+yzBc4C7jxBsPz5AiUWbFoWJv+lYtQlOCjagNjFDCMz3XqDIJvyDmxNgsgCUbnJsz6NQLCydnwcsHvk+v8iOZjMUs=
  file: NEKit.framework.zip
  on:
    repo: zhuhaow/NEKit
    tags: true
env:
  global:
    secure: fw5LXsRbFTKHTwPDaSZFbmw9Qj3/lvphiItdeDDmT52UsbcLlLjHk8etuUtd+ZWvI2mweahwrY0uI7hhOhKLdTSwDv/5quHpoMOpIh6x5ZldK5+CkSBtqCSbLMDrx+a/X7vu1U4sdWWskYIcGsDHeGeFTSfFLZHIexbJ21b2DADxAcPlatdMCOxqfAhoeFsqBykfY3fhwn8pkuXznGqhO2xgi2uSHuPxqfG9l6icLdi38WLlOCBNRyUFLJ8Pop850d7PRTHkvsVYPhppr0lB1xSWpBs46HSurrb3WWo9OhZhg2IuVtj+Tn4Y4O49G0aFq8NRHtJ2hTSSAbELfwokjD6Cryx2TDYoLsEP8GIDF4B8h2il0uiBIgbvLISW/xcncOmXshJoKa2qUDg+4riw/DxgGPSSOzNWyJAeGUc9KGzl1e6uEnE4LYAC2kcqCOsZ+O4WJamRf2whi/ADb3VKF47MhOxaDoF2eABLmm3hmsc1/jRAa+mGfk1slPVxZvGKKVEDCIl0Xu26rP1pvoheCv6KxRbA8Yz33qsv4xM+3SA1GZRWxAe+1YnodnuDPuAn6QiHlRtwB01KXnGTYH2hLC7astIG75p0PCnuPNitWJ3ULUpvMNyxQfbrxXg2aqhxJ/PZ0Vt5U4mvvYZhaSnXvI9+sl6aWc2hViXPp4u++1c=
